export const LocalStorageKeys = {
	imageHostConfig: "void-verified-image-host-config",
	readNotifications: "void-verified-read-notifications",
	notificationsConfig: "void-verified-notifications-config",
	notificationsConfigQuickAccess: "void-verified-quick-access-notifications-config",
	notificationRelationsCache: "void-verified-notification-relations",
	notificationDeadLinkRelationsCache:  "void-verified-notification-deadlink-relations",
	quickStartConfig: "void-verified-quick-start-config",
	gifKeyboardConfig: "void-verified-gif-keyboard",
	globalCSS:  "void-verified-global-css",
	goalsConfig: "void-verified-goals",
	layouts: "void-verified-layouts",
	miniProfileCache: "void-verified-mini-profile-cache",
	miniProfileConfig: "void-verified-mini-profile-config",
	verifiedUSers: "void-verified-users",
	settings: "void-verified-settings",
	toasterConfig: "void-verified-toaster-config",
	collapsedContainers: "void-verified-collapsed-containers",
	timeConfig: "void-verified-time-config",
	drafts: "void-verified-markdown-drafts"
}
